# Generated by Django 3.1 on 2022-06-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prfileImage', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('fullName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('targNo', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car')),
                ('dateTimeReg', models.DateTimeField(max_length=255)),
                ('desc', models.TextField(max_length=255)),
                ('theOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
