# Generated by Django 3.1 on 2022-06-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220606_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='targNo',
            new_name='plateNo',
        ),
        migrations.AlterField(
            model_name='car',
            name='dateTimeReg',
            field=models.DateTimeField(),
        ),
    ]
