# Generated by Django 3.1 on 2022-06-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220606_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeReg', models.DateTimeField()),
                ('desc', models.TextField()),
                ('fixed', models.BooleanField(default=False)),
                ('penallyMoney', models.FloatField(default=0)),
                ('paided', models.BooleanField(default=False)),
                ('theCar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
            ],
        ),
    ]
