# Generated by Django 4.0.4 on 2022-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='fines',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
