# Generated by Django 4.0.4 on 2022-06-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fines_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
