# Generated by Django 4.0.4 on 2022-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinesReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fineTitle', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('info', models.TextField()),
            ],
        ),
    ]
