# Generated by Django 4.0.4 on 2022-06-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_finesreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fines',
            name='fineTitle',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='penallyMoney',
        ),
        migrations.AddField(
            model_name='fines',
            name='theFine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.finesreg'),
            preserve_default=False,
        ),
    ]
