# Generated by Django 4.0.4 on 2022-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fines_imagearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('carName', models.CharField(blank=True, max_length=255, null=True)),
                ('carPlate', models.CharField(blank=True, max_length=255, null=True)),
                ('imageArea', models.ImageField(blank=True, null=True, upload_to='emergencyImages')),
                ('desc', models.TextField(blank=True, null=True)),
                ('dateR', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
